const:
- platform: linux
- lua_lib: /Projects/steven/install/lua/5.3.1/lib/liblua.a
- lua_include: /Projects/steven/install/lua/5.3.1/include
- I: -I${lua_include}

rules:
- combine: deps/${platform}/bin/luastatic $in $I

tasks:
- rule: combine
  in:
  - module/lua/automagical.lua
  - $lua_lib
  out: "auto"
